"""Weekly filter-optimization agent. Reads 'Rejected by Tim' Airtable, analyzes
rejection patterns + currently-active filter rules, asks Claude to propose
ADDITIONS to filter logic, posts the proposal as a GitHub issue (or to a Slack
webhook if configured) for Tim to review.

This runs weekly on Fridays. Tim reviews the proposal and either:
- Accepts → applies suggested filter rule manually (Claude generates the diff)
- Rejects → marks 'Processed by Optimizer' checkbox so it's not re-proposed

Designed to be safe: Claude PROPOSES, Tim DECIDES. Never auto-modifies code.
"""

import os, sys, json, urllib.request

AT_BASE = os.environ['AT_BASE'] if 'AT_BASE' in os.environ else 'appv6jhEzhGaAITcs'
RJ_TABLE = 'tblMewF15iP58sJHm'
AT_TOKEN = os.environ['AT_TOKEN']
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
GH_PAT = os.environ.get('GH_PAT', '')

# Fetch unprocessed rejections
print('Fetching unprocessed rejections from Airtable...', file=sys.stderr)
rejections = []
url = f'https://api.airtable.com/v0/{AT_BASE}/{RJ_TABLE}?filterByFormula=NOT(%7BProcessed%20by%20Optimizer%7D)&pageSize=100'
while url:
    req = urllib.request.Request(url, headers={'Authorization': f'Bearer {AT_TOKEN}'})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = json.loads(r.read())
    for record in data.get('records', []):
        rejections.append({**record['fields'], '_record_id': record['id']})
    offset = data.get('offset')
    url = f'https://api.airtable.com/v0/{AT_BASE}/{RJ_TABLE}?filterByFormula=NOT(%7BProcessed%20by%20Optimizer%7D)&pageSize=100&offset={offset}' if offset else None

print(f'{len(rejections)} unprocessed rejections', file=sys.stderr)
if len(rejections) < 3:
    print('Not enough rejections to justify optimization run (need ≥3). Skipping.', file=sys.stderr)
    sys.exit(0)

# Read current triage.py — give Claude full context on existing filters
with open(os.path.join(os.path.dirname(__file__), 'triage.py')) as f:
    triage_code = f.read()

# Build prompt
rejections_summary = '\n'.join(
    f"- {r.get('Address','?')} (Tier {r.get('Tier (was)','?')}, ${r.get('List Price',0):,}): "
    f"{r.get('Reason','?')} — {r.get('Notes','(no notes)')[:200]}"
    for r in rejections
)

prompt = f"""You are reviewing operator-rejected properties from a creative-finance wholesaling triage pipeline (Richard Taylor's HMHW method on BBC Lightning Leads). Your job: identify PATTERNS in the rejections and propose ADDITIONS to the filter rules so these mistakes don't repeat.

# Recent rejections ({len(rejections)} total):

{rejections_summary}

# Current triage filter pipeline (Python):

```python
{triage_code[:12000]}
```

(truncated for context; full file at scripts/triage.py)

# Your task

1. Identify CLUSTERS of rejections that share a pattern (e.g. "3 rejections all were REO listed by Auction.com → expand auction-agent keyword list").
2. For each cluster of ≥2, propose ONE specific filter addition. Be precise:
   - Which Python file / function to modify (e.g., `NON_RESIDENTIAL_TYPES` tuple, `condition_risk_flags()` heuristic, `AUCTION_AGENT_KEYWORDS`)
   - The exact diff (current → proposed)
   - Confidence (HIGH / MEDIUM / LOW based on cluster size + pattern strength)
3. Skip singletons (1 rejection that doesn't fit a pattern — too risky to filter on)
4. Output as markdown with one section per proposal. Include a "Risk" line per proposal noting what legitimate properties might also be filtered.

Format:
```
# Optimization proposal — {len(rejections)} rejections reviewed

## Proposal 1: [short title]
- **Pattern (N rejections):** brief description
- **Examples:** address1, address2
- **Proposed change:** specific code edit
- **Risk:** what else this might catch
- **Confidence:** HIGH/MEDIUM/LOW

(repeat for each proposal)

## Singletons not actioned
- list of 1-off rejections that didn't pattern
```
"""

# Call Claude
print('Calling Claude for optimization proposal...', file=sys.stderr)
body = {
    'model': 'claude-sonnet-4-6',
    'max_tokens': 4000,
    'messages': [{'role': 'user', 'content': prompt}]
}
req = urllib.request.Request('https://api.anthropic.com/v1/messages',
    method='POST', data=json.dumps(body).encode(),
    headers={'x-api-key': ANTHROPIC_API_KEY,
             'anthropic-version': '2023-06-01',
             'content-type': 'application/json'})
with urllib.request.urlopen(req, timeout=120) as r:
    resp = json.loads(r.read())

proposal_md = resp['content'][0]['text']
print('\n===== CLAUDE PROPOSAL =====\n', file=sys.stderr)
print(proposal_md)

# Post as a GitHub issue if PAT set
if GH_PAT:
    print('\nPosting as GitHub issue...', file=sys.stderr)
    issue_body = {
        'title': f'Filter optimization proposal — {len(rejections)} rejections reviewed',
        'body': proposal_md + f'\n\n---\nGenerated by `scripts/optimize_filters.py`. Review & accept manually.\nAfter applying changes, mark rejections as "Processed by Optimizer" in Airtable.'
    }
    req = urllib.request.Request('https://api.github.com/repos/timfarr-ai/rt-companion/issues',
        method='POST', data=json.dumps(issue_body).encode(),
        headers={'Authorization': f'Bearer {GH_PAT}',
                 'Accept': 'application/vnd.github+json',
                 'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            issue = json.loads(r.read())
        print(f'Issue created: {issue.get("html_url")}', file=sys.stderr)
    except Exception as e:
        print(f'Failed to create issue: {e}', file=sys.stderr)
else:
    print('\nGH_PAT not set — proposal not posted as issue. Copy from stdout above.', file=sys.stderr)
